name: env
channels:
  - conda-forge
dependencies:
  - python=3.12.9
  - numpy=2.2.2
  - scipy=1.15.2
  - joblib=1.4.2
  - threadpoolctl=3.5.0
  - scikit-learn=1.6.1
  - matplotlib=3.10.0
  - pandas=2.2.2
  - seaborn=0.13.2
  - jupyterlab=4.3.5
  - notebook=7.3.2